const express = require('express');
const router = express.Router();
const mediaDerivativeController = require('../controllers/mediaDerivative.controller');
const authMiddleware = require('../middleware/auth.middleware');

// Применяем аутентификацию ко всем маршрутам
router.use(authMiddleware);

// GET /media/:mediaId/derivatives - получить все производные для медиафайла
router.get('/:mediaId/derivatives', mediaDerivativeController.getMediaDerivatives);

// GET /media/:mediaId/derivatives/:derivativeType - получить конкретный тип производного
router.get('/:mediaId/derivatives/:derivativeType', mediaDerivativeController.getMediaDerivative);

// POST /media/:mediaId/derivatives - создать производный файл (с загрузкой)
router.post('/:mediaId/derivatives', 
  mediaDerivativeController.constructor.getUploadMiddleware(),
  mediaDerivativeController.createMediaDerivative
);

// POST /media/:mediaId/thumbnail - создать thumbnail (с загрузкой)
router.post('/:mediaId/thumbnail',
  mediaDerivativeController.constructor.getUploadMiddleware(),
  mediaDerivativeController.createThumbnail
);

// POST /media/:mediaId/blur-hash - генерировать blur hash
router.post('/:mediaId/blur-hash', mediaDerivativeController.generateBlurHash);

// POST /media/:mediaId/derivatives/bulk - массовое создание производных
router.post('/:mediaId/derivatives/bulk', mediaDerivativeController.bulkCreateDerivatives);

// POST /media/:mediaId/auto-generate - автоматически генерировать все производные
router.post('/:mediaId/auto-generate', mediaDerivativeController.autoGenerateDerivatives);

// GET /media/:mediaId/derivatives/stats - получить статистику производных
router.get('/:mediaId/derivatives/stats', mediaDerivativeController.getDerivativeStats);

// DELETE /media/:mediaId/derivatives - удалить все производные для медиафайла
router.delete('/:mediaId/derivatives', mediaDerivativeController.deleteAllDerivatives);

// DELETE /media/derivatives/:derivativeId - удалить конкретный производный файл
router.delete('/derivatives/:derivativeId', mediaDerivativeController.deleteMediaDerivative);

module.exports = router;
