const express = require('express');
const router = express.Router();
const mediaDerivativeController = require('../controllers/mediaDerivative.controller');
const { authenticateToken } = require('../middleware/auth.middleware');

// GET /media/:mediaId/derivatives - get all derivatives for media file
router.get('/:mediaId/derivatives', authenticateToken, mediaDerivativeController.getMediaDerivatives);

// GET /media/:mediaId/derivatives/:derivativeType - get specific derivative type
router.get('/:mediaId/derivatives/:derivativeType', authenticateToken, mediaDerivativeController.getMediaDerivative);

// POST /media/:mediaId/derivatives - create derivative file (with upload)
router.post('/:mediaId/derivatives', 
  authenticateToken,
  mediaDerivativeController.constructor.getUploadMiddleware(),
  mediaDerivativeController.createMediaDerivative
);

// POST /media/:mediaId/thumbnail - create thumbnail (with upload)
router.post('/:mediaId/thumbnail',
  authenticateToken,
  mediaDerivativeController.constructor.getUploadMiddleware(),
  mediaDerivativeController.createThumbnail
);

// POST /media/:mediaId/blur-hash - generate blur hash
router.post('/:mediaId/blur-hash', authenticateToken, mediaDerivativeController.generateBlurHash);

// POST /media/:mediaId/derivatives/bulk - bulk create derivatives
router.post('/:mediaId/derivatives/bulk', authenticateToken, mediaDerivativeController.bulkCreateDerivatives);

// POST /media/:mediaId/auto-generate - automatically generate all derivatives
router.post('/:mediaId/auto-generate', authenticateToken, mediaDerivativeController.autoGenerateDerivatives);

// GET /media/:mediaId/derivatives/stats - get derivatives statistics
router.get('/:mediaId/derivatives/stats', authenticateToken, mediaDerivativeController.getDerivativeStats);

// DELETE /media/:mediaId/derivatives - delete all derivatives for media file
router.delete('/:mediaId/derivatives', authenticateToken, mediaDerivativeController.deleteAllDerivatives);

// DELETE /media/derivatives/:derivativeId - delete specific derivative file
router.delete('/derivatives/:derivativeId', authenticateToken, mediaDerivativeController.deleteMediaDerivative);

module.exports = router;
