import React, { useState, useEffect } from 'react';
import { MediaDerivative } from '../../types/models';
import mediaService from '../../services/media.service';
import styles from './MediaDerivativeViewer.module.css';

interface MediaDerivativeViewerProps {
  mediaId: string;
  showControls?: boolean;
  onDerivativeCreate?: (derivative: MediaDerivative) => void;
  onDerivativeDelete?: (derivativeId: string) => void;
}

export const MediaDerivativeViewer: React.FC<MediaDerivativeViewerProps> = ({
  mediaId,
  showControls = true,
  onDerivativeCreate,
  onDerivativeDelete
}) => {
  const [derivatives, setDerivatives] = useState<MediaDerivative[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [selectedType, setSelectedType] = useState<string | null>(null);
  const [stats, setStats] = useState<any>(null);

  useEffect(() => {
    loadDerivatives();
    loadStats();
  }, [mediaId]);

  const loadDerivatives = async () => {
    try {
      setLoading(true);
      setError(null);
      const response = await mediaService.getMediaDerivatives(mediaId);
      setDerivatives(response.data || []);
    } catch (err) {
      console.error('Error loading derivatives:', err);
      setError('Ошибка при загрузке производных файлов');
    } finally {
      setLoading(false);
    }
  };

  const loadStats = async () => {
    try {
      const response = await mediaService.getDerivativeStats(mediaId);
      setStats(response);
    } catch (err) {
      console.error('Error loading stats:', err);
    }
  };

  const handleDelete = async (derivativeId: string) => {
    if (!window.confirm('Вы уверены, что хотите удалить этот производный файл?')) {
      return;
    }

    try {
      await mediaService.deleteMediaDerivative(derivativeId);
      setDerivatives(derivatives.filter(d => d.id !== derivativeId));
      onDerivativeDelete?.(derivativeId);
      await loadStats(); // Обновляем статистику
    } catch (error) {
      console.error('Error deleting derivative:', error);
      alert('Ошибка при удалении файла');
    }
  };

  const handleAutoGenerate = async () => {
    try {
      await mediaService.autoGenerateDerivatives(mediaId);
      alert('Автоматическая генерация запущена');
      // В реальном приложении здесь был бы polling для обновления статуса
    } catch (error) {
      console.error('Error auto-generating:', error);
      alert('Ошибка при запуске автоматической генерации');
    }
  };

  const getTypeIcon = (type: string) => {
    switch (type) {
      case 'thumbnail':
        return '🖼️';
      case 'preview':
        return '👁️';
      case 'optimized':
        return '⚡';
      case 'webp':
        return '🌐';
      case 'blur_hash':
        return '🌫️';
      default:
        return '📄';
    }
  };

  const getTypeName = (type: string) => {
    switch (type) {
      case 'thumbnail':
        return 'Миниатюра';
      case 'preview':
        return 'Превью';
      case 'optimized':
        return 'Оптимизированный';
      case 'webp':
        return 'WebP';
      case 'blur_hash':
        return 'Blur Hash';
      default:
        return type;
    }
  };

  const formatFileSize = (bytes: number) => {
    if (!bytes) return 'Не указано';
    const units = ['Б', 'КБ', 'МБ', 'ГБ'];
    let size = bytes;
    let unitIndex = 0;
    
    while (size >= 1024 && unitIndex < units.length - 1) {
      size /= 1024;
      unitIndex++;
    }
    
    return `${size.toFixed(1)} ${units[unitIndex]}`;
  };

  const getDerivativeUrl = (derivative: MediaDerivative) => {
    return mediaService.getDerivativeUrl(derivative);
  };

  const filteredDerivatives = selectedType 
    ? derivatives.filter(d => d.derivative_type === selectedType)
    : derivatives;

  const availableTypes = [...new Set(derivatives.map(d => d.derivative_type))];

  if (loading) {
    return (
      <div className={styles.loading}>
        <div className={styles.spinner}></div>
        <span>Загрузка производных файлов...</span>
      </div>
    );
  }

  if (error) {
    return (
      <div className={styles.error}>
        <span>❌ {error}</span>
        <button onClick={loadDerivatives} className={styles.retryButton}>
          🔄 Повторить
        </button>
      </div>
    );
  }

  return (
    <div className={styles.derivativeViewer}>
      {/* Header with Stats */}
      <div className={styles.header}>
        <h3>📁 Производные файлы</h3>
        {stats && (
          <div className={styles.stats}>
            <span>Всего: {stats.totalDerivatives}</span>
            <span>Размер: {formatFileSize(stats.totalSize)}</span>
          </div>
        )}
      </div>

      {/* Controls */}
      {showControls && (
        <div className={styles.controls}>
          <div className={styles.typeFilter}>
            <button
              className={`${styles.filterButton} ${!selectedType ? styles.active : ''}`}
              onClick={() => setSelectedType(null)}
            >
              Все ({derivatives.length})
            </button>
            {availableTypes.map(type => (
              <button
                key={type}
                className={`${styles.filterButton} ${selectedType === type ? styles.active : ''}`}
                onClick={() => setSelectedType(type)}
              >
                {getTypeIcon(type)} {getTypeName(type)} ({derivatives.filter(d => d.derivative_type === type).length})
              </button>
            ))}
          </div>
          
          <div className={styles.actions}>
            <button 
              onClick={handleAutoGenerate}
              className={styles.autoGenerateButton}
            >
              ⚡ Автогенерация
            </button>
            <button onClick={loadDerivatives} className={styles.refreshButton}>
              🔄 Обновить
            </button>
          </div>
        </div>
      )}

      {/* Derivatives List */}
      <div className={styles.derivativesList}>
        {filteredDerivatives.length === 0 ? (
          <div className={styles.empty}>
            <div className={styles.emptyIcon}>📄</div>
            <h4>
              {selectedType 
                ? `Нет производных файлов типа "${getTypeName(selectedType)}"` 
                : 'Производных файлов нет'
              }
            </h4>
            <p>
              {selectedType 
                ? 'Попробуйте изменить фильтр или создать новые файлы'
                : 'Создайте производные файлы для улучшения производительности'
              }
            </p>
            {!selectedType && showControls && (
              <button 
                onClick={handleAutoGenerate}
                className={styles.emptyActionButton}
              >
                ⚡ Создать автоматически
              </button>
            )}
          </div>
        ) : (
          <div className={styles.derivativesGrid}>
            {filteredDerivatives.map(derivative => (
              <div key={derivative.id} className={styles.derivativeCard}>
                <div className={styles.cardHeader}>
                  <span className={styles.typeIcon}>
                    {getTypeIcon(derivative.derivative_type)}
                  </span>
                  <span className={styles.typeName}>
                    {getTypeName(derivative.derivative_type)}
                  </span>
                  {showControls && (
                    <button
                      onClick={() => handleDelete(derivative.id)}
                      className={styles.deleteButton}
                      title="Удалить"
                    >
                      🗑️
                    </button>
                  )}
                </div>

                <div className={styles.cardContent}>
                  {derivative.derivative_type === 'blur_hash' ? (
                    <div className={styles.blurHashPreview}>
                      <div className={styles.blurHashCode}>
                        {derivative.metadata?.blur_hash || 'Blur Hash'}
                      </div>
                    </div>
                  ) : (
                    <div className={styles.imagePreview}>
                      <img
                        src={getDerivativeUrl(derivative)}
                        alt={`${getTypeName(derivative.derivative_type)} preview`}
                        className={styles.previewImage}
                        onError={(e) => {
                          (e.target as HTMLImageElement).src = '/placeholder-image.png';
                        }}
                      />
                    </div>
                  )}

                  <div className={styles.cardMeta}>
                    {derivative.width && derivative.height && (
                      <span className={styles.dimensions}>
                        📐 {derivative.width}×{derivative.height}
                      </span>
                    )}
                    {derivative.size_bytes && (
                      <span className={styles.fileSize}>
                        💾 {formatFileSize(derivative.size_bytes)}
                      </span>
                    )}
                    {derivative.format && (
                      <span className={styles.format}>
                        🔧 {derivative.format.toUpperCase()}
                      </span>
                    )}
                    {derivative.quality && (
                      <span className={styles.quality}>
                        ⭐ Качество: {derivative.quality}%
                      </span>
                    )}
                  </div>

                  {derivative.metadata && Object.keys(derivative.metadata).length > 0 && (
                    <div className={styles.metadata}>
                      <details className={styles.metadataDetails}>
                        <summary>📋 Метаданные</summary>
                        <pre className={styles.metadataContent}>
                          {JSON.stringify(derivative.metadata, null, 2)}
                        </pre>
                      </details>
                    </div>
                  )}
                </div>

                <div className={styles.cardActions}>
                  {derivative.derivative_type !== 'blur_hash' && (
                    <a
                      href={getDerivativeUrl(derivative)}
                      target="_blank"
                      rel="noopener noreferrer"
                      className={styles.viewButton}
                    >
                      👁️ Просмотр
                    </a>
                  )}
                  <a
                    href={getDerivativeUrl(derivative)}
                    download
                    className={styles.downloadButton}
                  >
                    📥 Скачать
                  </a>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Stats Details */}
      {stats && stats.byType && Object.keys(stats.byType).length > 0 && (
        <div className={styles.detailedStats}>
          <h4>📊 Статистика по типам</h4>
          <div className={styles.statsGrid}>
            {Object.entries(stats.byType).map(([type, typeStats]: [string, any]) => (
              <div key={type} className={styles.statCard}>
                <div className={styles.statHeader}>
                  {getTypeIcon(type)} {getTypeName(type)}
                </div>
                <div className={styles.statContent}>
                  <span>Количество: {typeStats.count}</span>
                  <span>Размер: {formatFileSize(typeStats.totalSize)}</span>
                  <span>Средний: {formatFileSize(typeStats.avgSize)}</span>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
};
